### PR TITLE
Prevent negative timestamp calculations from crashing in TelemetryEvent.

### PR DESCRIPTION
**Pull request by justindarc**

### CODE REVIEW

**Comment by garvankeeley** [comment]
Actually, I have another thought on this patch, one min, just checking something

**Comment by garvankeeley** [comment]
Could `Date().timeIntervalSince(TelemetryEvent.AppLaunchTimestamp)` be assigned to a var and checked to see if it is negative first? Am I overthinking this?

**Comment by justindarc** [comment]
It doesn't matter. We just need a value in there to indicate how long it has been since the app launched. We have no idea why this is sometimes negative, seems like a rounding bug. So, the proper thing to do is just clamp it to `0` which is what we're doing here.

**Comment by garvankeeley** [comment]
`max(0, UInt64(Date().timeIntervalSince(TelemetryEvent.AppLaunchTimestamp) * 1000))`
should that be:
`UInt64(max(0, Date().timeIntervalSince(TelemetryEvent.AppLaunchTimestamp) * 1000))`

**Comment by justindarc** [comment]
It shouldn't matter. The compiler knows what to do here because it can infer the type from the 2nd arg.

**Comment by justindarc** [comment]
Also, I already hit merge :-)

**Comment by garvankeeley** [comment]
UInt64(negative) crashes though. And if `Date().timeIntervalSince(TelemetryEvent.AppLaunchTimestamp)` is negative this code will still crash. Sorry I should I have caught this before the r+

**Comment by justindarc** [comment]
Ahhh good catch.. I'll push up a fix

**Pull request merged**
